### ISSUE TITLE
There is no logout capability

### ISSUE THREAD

**Issue by alexziskind1** [NativeScript/template-patient-care-ng#15]
Logging out is pretty fundamental to an authenticated app. There should be a way to log out.
Thanks.

**Comment by manoldonev** [comment]
Kinvey SDK provides support for logging out the authenticated user:

``` ts
import { Kinvey } from "kinvey-nativescript-sdk";

Kinvey.User.logout();
```

We will also consider how to extend the app design to incorporate this functionality out-of-the-box for one of the future versions of the app template.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#6050
